### ISSUE TITLE
CORS Error with API endpoint

### ISSUE THREAD

**Issue by baruchvlz** [mcmakler/frontend_interview_test#3]
Hello, 

I was invited to do the test. I have the HTML/CSS pretty much done, but when I try to do a HTTP GET request to the endpoint from my local I get a `'Access-Control-Allow-Origin'` error. To my understanding this is an issue from the server? I've been looking through the repo to see if I can find something referring to this but haven't found anything.

I think it's worth mentioning that I'm doing the test with an AngularCLI generated project so it's being done outside of this repo with a submodule (which hasn't been added yet). Also, I'm running the local environment on port `8080`, I can't run it on port `80` because I have some apache projects that require that port.

Cheers.

**EDIT**
I'm able to visit the URL from my browser, so if it's ok with you guys I can copy a snapshot of the response and save it as a JSON file on my local and work with that instead. Let me know.

**Comment by OskHa** [comment]
Hi. With WebPack it is possible to setup proxy to avoid CORS issues. But thats a good point, we will solve that.

**Comment by baruchvlz** [comment]
Oh, well that's embarrassing. I haven't used webpack enough. Thanks for the clarification. 

Cheers.
